合并 ConfigAndCustom 分支

diff --git a/trunk/user/shadowsocks/scripts/ss-rules b/trunk/user/shadowsocks/scripts/ss-rules
--- a/trunk/user/shadowsocks/scripts/ss-rules
+++ b/trunk/user/shadowsocks/scripts/ss-rules
@@ -1,268 +1,209 @@
 #!/bin/sh
 #
-# Copyright (C) 2014-2017 Jian Chang <aa65535@live.com>
-#
-# This is free software, licensed under the GNU General Public License v3.
-# See /LICENSE for more information.
-#
+# Copyright (C) 2021 GH-X
 
-modprobe xt_TPROXY
-modprobe xt_set
-modprobe ip_set_hash_ip
-modprobe ip_set_hash_net
-modprobe ip_set_hash_mac
+private_addr="0.0.0.0/8          10.0.0.0/8         100.64.0.0/10      127.0.0.0/8
+              169.254.0.0/16     172.16.0.0/12      192.0.0.0/24       192.0.2.0/24
+              192.31.196.0/24    192.52.193.0/24    192.88.99.0/24     192.168.0.0/16
+              192.175.48.0/24    198.18.0.0/15      198.51.100.0/24    203.0.113.0/24
+              224.0.0.0/4        240.0.0.0/4        255.255.255.255/32"
 
-usage() {
-	cat <<-EOF
-		Usage: ss-rules [options]
+iptn="iptables -t nat"
+iptf="iptables -t filter"
+iptm="iptables -t mangle"
+ipt_n="/tmp/ss-rules_iptables_nat"
+ipt_f="/tmp/ss-rules_iptables_filter"
+ipt_m="/tmp/ss-rules_iptables_mangle"
 
-		Valid options are:
+routemark="0x64"
+ruletable="100"
 
-		    -s <server_ips>         ip address of shadowsocks remote server
-		    -l <local_port>         port number of shadowsocks local server
-		    -S <server_ips>         ip address of shadowsocks remote UDP server
-		    -L <local_port>         port number of shadowsocks local UDP server
-		    -B <ip_list_file>       a file whose content is bypassed ip list
-		    -b <wan_ips>            wan ip of will be bypassed
-		    -W <ip_list_file>       a file whose content is forwarded ip list
-		    -w <wan_ips>            wan ip of will be forwarded
-		    -I <interface>          proxy only for the given interface
-		    -d <target>             the default target of lan access control
-		    -a <lan_hosts>          mac addr of access control, need a prefix to
-		                            define proxy type
-		    -e <extra_args>         extra arguments for iptables
-		    -o                      apply the rules to the OUTPUT chain
-		    -O                      apply the global rules to the OUTPUT chain
-		    -u                      enable udprelay mode, TPROXY is required
-		    -U                      enable udprelay mode, using different IP
-		                            and ports for TCP and UDP
-		    -f                      flush the rules
-		    -h                      show this help message and exit
-EOF
-	exit $1
+connlimitsrc="-m connlimit --connlimit-upto 256 --connlimit-mask 32 --connlimit-saddr"
+
+flush_rules()
+{
+echo -1000 > /proc/$$/oom_score_adj
+iptables-save -c | grep -v -E "SSP_|TPROXY" | iptables-restore -c
+ipset destroy servers
+ipset destroy private
+ipset destroy gfwlist
+ipset destroy chnlist
+ip route del local default dev lo table $ruletable
+ip rule del fwmark $routemark table $ruletable
+ip route flush cache
+return 0
 }
 
-loger() {
-	# 1.alert 2.crit 3.err 4.warn 5.notice 6.info 7.debug
-	logger -st ss-rules[$$] -p$1 $2
-}
-
-flush_rules() {
-	iptables-save -c | grep -v "SS_SPEC" | iptables-restore -c
-	#if command -v ip >/dev/null 2>&1; then
-		ip rule del fwmark 100 lookup 100 2>/dev/null
-		ip route del local default dev lo table 100 2>/dev/null
-	#fi
-	for setname in $(ipset -n list | grep "ss_spec"); do
-		ipset destroy $setname 2>/dev/null
-	done
-	FWI="/tmp/shadowsocks_iptables.save"
-	[ -n "$FWI" ] && echo '# firewall include file' >$FWI
-	chmod +x $FWI
-	return 0
-}
-
-ipset_init() {
-	ipset -! restore <<-EOF || return 1
-		create ss_spec_src_ac hash:net hashsize 64
-		create ss_spec_src_bp hash:net hashsize 64
-		create ss_spec_src_fw hash:net hashsize 64
-		create ss_spec_dst_sp hash:net hashsize 64
-		create ss_spec_dst_bp hash:net hashsize 64
-		create ss_spec_dst_fw hash:net hashsize 64
-		$(gen_lan_host_ipset_entry)
-		$(gen_special_purpose_ip | sed -e "s/^/add ss_spec_dst_sp /")
-		$(sed -e "s/^/add ss_spec_dst_bp /" ${WAN_BP_LIST:=/dev/null} 2>/dev/null)
-		$(for ip in $WAN_BP_IP; do echo "add ss_spec_dst_bp $ip"; done)
-		$(sed -e "s/^/add ss_spec_dst_fw /" ${WAN_FW_LIST:=/dev/null} 2>/dev/null)
-		$(for ip in $WAN_FW_IP; do echo "add ss_spec_dst_fw $ip"; done)
-EOF
-	return 0
-}
-
-ipt_nat() {
-	include_ac_rules nat
-	ipt="iptables -t nat"
-	$ipt -A SS_SPEC_WAN_FW -p tcp \
-		-j REDIRECT --to-ports $local_port || return 1
-	if [ -n "$OUTPUT" ]; then
-		$ipt -N SS_SPEC_WAN_DG
-		$ipt -A SS_SPEC_WAN_DG -m set --match-set ss_spec_dst_sp dst -j RETURN
-		$ipt -A SS_SPEC_WAN_DG -p tcp $EXT_ARGS -j $OUTPUT
-		$ipt -I OUTPUT 1 -p tcp -j SS_SPEC_WAN_DG
-	fi
-	return $?
-}
-
-ipt_mangle() {
-	[ -n "$TPROXY" ] || return 0
-	if !(lsmod | grep -q TPROXY ); then
-		loger 4 "TPROXY or ip not found."
-		return 0
-	fi
-	ip rule add fwmark 100 lookup 100
-	ip route add local default dev lo table 100
-	include_ac_rules mangle
-	iptables -t mangle -A SS_SPEC_WAN_FW -p udp \
-		-j TPROXY --on-port $LOCAL_PORT --tproxy-mark 100
-	return $?
-}
-
-export_ipt_rules() {
-	[ -n "$FWI" ] || return 0
-	cat <<-CAT >>$FWI
-	iptables-save -c | grep -v "SS_SPEC" | iptables-restore -c
-	iptables-restore -n <<-EOF
-	$(iptables-save | grep -E "SS_SPEC|^\*|^COMMIT" |\
-			sed -e "s/^-A \(OUTPUT\|PREROUTING\)/-I \1 1/")
-	EOF
-CAT
-	return $?
-}
-
-gen_lan_host_ipset_entry() {
-	for host in $LAN_HOSTS; do
-		case "${host:0:1}" in
-			b|B)
-				echo add ss_spec_src_bp ${host:2}
-				;;
-			g|G)
-				echo add ss_spec_src_fw ${host:2}
-				;;
-			n|N)
-				echo add ss_spec_src_ac ${host:2}
-				;;
-		esac
-	done
-}
-
-gen_special_purpose_ip() {
-	cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
-		0.0.0.0/8
-		10.0.0.0/8
-		100.64.0.0/10
-		127.0.0.0/8
-		169.254.0.0/16
-		172.16.0.0/12
-		192.0.0.0/24
-		192.0.2.0/24
-		192.31.196.0/24
-		192.52.193.0/24
-		192.88.99.0/24
-		192.168.0.0/16
-		192.175.48.0/24
-		198.18.0.0/15
-		198.51.100.0/24
-		203.0.113.0/24
-		224.0.0.0/4
-		240.0.0.0/4
-		255.255.255.255
-		$server
-		$SERVER
+gen_ipset()
+{
+ipset -! restore <<-EOF || return 1
+  create servers hash:net hashsize 64 maxelem 256
+  create private hash:net hashsize 64 maxelem 128
+  create gfwlist hash:net hashsize 1024 maxelem 65536
+  create chnlist hash:net hashsize 16384 maxelem 1000000
+  $(for privateaddr in $private_addr; do echo "add private $privateaddr"; done)
+  $(for blackip in $black_ip; do echo "add gfwlist $blackip"; done)
+  $(for whiteip in $white_ip; do echo "add chnlist $whiteip"; done)
+  $(cat ${gfw_list:=/dev/null} 2>/dev/null | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" | sed -e "s/^/add gfwlist /")
+  $(cat ${chn_list:=/dev/null} 2>/dev/null | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" | sed -e "s/^/add chnlist /")
+  $(cat ${chnexp_list:=/dev/null} 2>/dev/null | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" | sed -e "s/^/add chnlist /")
 EOF
 }
 
-include_ac_rules() {
-	local protocol=$([ "$1" = "mangle" ] && echo udp || echo tcp)
-	iptables-restore -n <<-EOF
-	*$1
-	:SS_SPEC_LAN_DG - [0:0]
-	:SS_SPEC_LAN_AC - [0:0]
-	:SS_SPEC_WAN_AC - [0:0]
-	:SS_SPEC_WAN_FW - [0:0]
-	-A SS_SPEC_LAN_DG -m set --match-set ss_spec_dst_sp dst -j RETURN
-	-A SS_SPEC_LAN_DG -p $protocol $EXT_ARGS -j SS_SPEC_LAN_AC
-	-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_fw src -j SS_SPEC_WAN_FW
-	-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_ac src -j SS_SPEC_WAN_AC
-	-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_bp src -j RETURN
-	-A SS_SPEC_LAN_AC -j ${LAN_TARGET:=SS_SPEC_WAN_AC}
-	-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_fw dst -j SS_SPEC_WAN_FW
-	-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_bp dst -j RETURN
-	-A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
-	$(gen_prerouting_rules $protocol)
-	COMMIT
+ipt_nat()
+{
+echo "*nat" > $ipt_n
+echo ":SSP_AGENT - [0:0]" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo ":SSP_AUTOC - [0:0]" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo ":SSP_AUTOG - [0:0]" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo ":SSP_AUTOM - [0:0]" >> $ipt_n
+echo ":SSP_OUTPUT - [0:0]" >> $ipt_n
+echo ":SSP_PREROUTING - [0:0]" >> $ipt_n
+echo ":SSP_RULES - [0:0]" >> $ipt_n
+echo "-A PREROUTING -j SSP_PREROUTING" >> $ipt_n
+echo "-A OUTPUT -j SSP_OUTPUT" >> $ipt_n
+echo "-A SSP_AGENT -p tcp $connlimitsrc -j REDIRECT --to-ports $local_port" >> $ipt_n
+echo "-A SSP_AGENT -j RETURN" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOC -p tcp $connlimitsrc -m connlimit --connlimit-above $DR2 --connlimit-mask 32 --connlimit-daddr -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOC -j RETURN" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOG -p tcp $connlimitsrc -m connlimit --connlimit-upto $DR2 --connlimit-mask 32 --connlimit-daddr -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOG -j RETURN" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOM -p tcp $connlimitsrc -m connlimit --connlimit-above $DR1 --connlimit-mask 32 --connlimit-daddr -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_AUTOM -j RETURN" >> $ipt_n
+echo "-A SSP_OUTPUT -p tcp -j SSP_RULES" >> $ipt_n
+echo "-A SSP_PREROUTING -p tcp -j SSP_RULES" >> $ipt_n
+echo "-A SSP_RULES -m state --state RELATED,ESTABLISHED -j RETURN" >> $ipt_n
+echo "-A SSP_RULES -m set --match-set private dst -j RETURN" >> $ipt_n
+echo "-A SSP_RULES -m set --match-set servers dst -j RETURN" >> $ipt_n
+[ "$serveraddr" == "0" ] || echo "-A SSP_RULES -d $serveraddr -j RETURN" >> $ipt_n
+[ "$agent_mode" == "1" ] && echo "-A SSP_RULES -m set --match-set chnlist dst -j RETURN" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_RULES -m set --match-set gfwlist dst -j SSP_AUTOG" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_RULES -m set --match-set chnlist dst -j SSP_AUTOC" >> $ipt_n
+[ "$agent_mode" != "2" ] && echo "-A SSP_RULES -j SSP_AGENT" >> $ipt_n
+[ "$agent_mode" == "2" ] && echo "-A SSP_RULES -j SSP_AUTOM" >> $ipt_n
+echo "COMMIT" >> $ipt_n && iptables-restore --noflush < $ipt_n && rm -rf $ipt_n || return 1
+}
+
+ipt_filter()
+{
+echo "*filter" > $ipt_f
+echo ":SSP_INPUT - [0:0]" >> $ipt_f
+echo "-A INPUT -j SSP_INPUT" >> $ipt_f
+echo "-A SSP_INPUT -m set --match-set private src -j RETURN" >> $ipt_f
+echo "-A SSP_INPUT -p tcp -m set --match-set servers src -m tcp --tcp-flags RST RST -m state --state RELATED,ESTABLISHED -m limit --limit 1/min --limit-burst 1 -j RETURN" >> $ipt_f
+echo "-A SSP_INPUT -p tcp -m set --match-set servers src -m tcp --tcp-flags RST RST -j DROP" >> $ipt_f
+[ "$serveraddr" == "0" ] || echo "-A SSP_INPUT -s $serveraddr -p tcp -m tcp --tcp-flags RST RST -m state --state RELATED,ESTABLISHED -m limit --limit 1/min --limit-burst 1 -j RETURN" >> $ipt_f
+[ "$serveraddr" == "0" ] || echo "-A SSP_INPUT -s $serveraddr -p tcp -m tcp --tcp-flags RST RST -j DROP" >> $ipt_f
+echo "-A SSP_INPUT -p tcp -m tcp --tcp-flags RST RST -m state --state INVALID,NEW -j DROP" >> $ipt_f
+echo "-A SSP_INPUT -j RETURN" >> $ipt_f
+echo "COMMIT" >> $ipt_f && iptables-restore --noflush < $ipt_f && rm -rf $ipt_f || return 1
+}
+
+ipt_mangle()
+{
+if !(lsmod | grep -q xt_TPROXY ); then
+  modprobe xt_TPROXY
+fi
+ip route add local default dev lo table $ruletable
+ip rule add fwmark $routemark table $ruletable
+$iptm -N SSP_AGENT
+$iptm -N SSP_OUTPUT
+$iptm -N SSP_PREROUTING
+$iptm -N SSP_RULES
+$iptm -I PREROUTING 1 -j SSP_PREROUTING
+$iptm -I OUTPUT 1 -j SSP_OUTPUT
+$iptm -A SSP_AGENT -j CONNMARK --restore-mark
+$iptm -A SSP_AGENT -j CONNMARK --set-mark $routemark
+$iptm -A SSP_AGENT -j CONNMARK --save-mark
+$iptm -A SSP_OUTPUT -p udp -j SSP_RULES
+$iptm -A SSP_PREROUTING -p udp -m mark --mark $routemark -j TPROXY --on-port $local_port
+$iptm -A SSP_PREROUTING -p udp -j SSP_RULES
+$iptm -A SSP_RULES -m mark --mark $routemark -j RETURN
+$iptm -A SSP_RULES -m set --match-set private dst -j RETURN
+$iptm -A SSP_RULES -m set --match-set servers dst -j RETURN
+[ "$serveraddr" == "0" ] || $iptm -A SSP_RULES -d $serveraddr -j RETURN
+[ "$agent_mode" == "2" ] && $iptm -A SSP_RULES -m set --match-set gfwlist dst -j SSP_AGENT
+[ "$agent_mode" != "0" ] && $iptm -A SSP_RULES -m set --match-set chnlist dst -j RETURN
+[ "$agent_mode" != "2" ] && $iptm -A SSP_RULES -j SSP_AGENT
+[ "$agent_mode" == "2" ] && $iptm -A SSP_RULES -j RETURN
+return 0
+}
+
+usage()
+{
+cat <<-EOF
+
+  ss-rules [选项] [赋值]            [说明]
+           -s     <serveraddr>      服务器地址      支持域名和IP/CIDR格式 赋值[0]禁用
+           -i     <local_port>      本地端口        
+           -g     <gfw_list>        黑名单地址列表  IP/CIDR格式
+           -c     <chn_list>        国内路由表      IP/CIDR格式
+           -e     <chnexp_list>     白名单地址列表  IP/CIDR格式
+           -b     <black_ip>        黑名单地址      多个IP/CIDR使用[,]隔开
+           -w     <white_ip>        白名单地址      多个IP/CIDR使用[,]隔开
+           -a     <agent_mode>      透明代理模式    全局代理[0] 国内路由表[1] 黑名单域名[2]
+                  <diversion_rate>  自动分流        灵敏[1] 准确[2]
+           -t                       透明代理协议    TCP[REDIRECT]
+           -m                       透明代理协议    TCP[REDIRECT] UDP[TPROXY]
+           -f                       清除规则        
+           -h                       显示帮助        
+
 EOF
+exit $1
 }
 
-gen_prerouting_rules() {
-	[ -z "$IFNAMES" ] && echo -I PREROUTING 1 -p $1 -j SS_SPEC_LAN_DG
-	for ifname in $IFNAMES; do
-		echo -I PREROUTING 1 -i $ifname -p $1 -j SS_SPEC_LAN_DG
-	done
-}
-
-while getopts ":s:l:S:L:B:b:W:w:I:d:a:e:oOuUfh" arg; do
-	case "$arg" in
-		s)
-			server=$(for ip in $OPTARG; do echo $ip; done)
-			;;
-		l)
-			local_port=$OPTARG
-			;;
-		S)
-			SERVER=$(for ip in $OPTARG; do echo $ip; done)
-			;;
-		L)
-			LOCAL_PORT=$OPTARG
-			;;
-		B)
-			WAN_BP_LIST=$OPTARG
-			;;
-		b)
-			WAN_BP_IP=$OPTARG
-			;;
-		W)
-			WAN_FW_LIST=$OPTARG
-			;;
-		w)
-			WAN_FW_IP=$OPTARG
-			;;
-		I)
-			IFNAMES=$OPTARG
-			;;
-		d)
-			LAN_TARGET=$OPTARG
-			;;
-		a)
-			LAN_HOSTS=$OPTARG
-			;;
-		e)
-			EXT_ARGS=$OPTARG
-			;;
-		o)
-			OUTPUT=SS_SPEC_WAN_AC
-			;;
-		O)
-			OUTPUT=SS_SPEC_WAN_FW
-			;;
-		u)
-			TPROXY=1
-			;;
-		U)
-			TPROXY=2
-			;;
-		f)
-			flush_rules
-			loger 5 "Flush Success!"
-			exit 0
-			;;
-		h)
-			usage 0
-			;;
-	esac
+logger -st "SSP[$$]Rules" "任务开始" && \
+while getopts ":s:i:g:c:e:b:w:a:tmfh" arg; do
+  case "$arg" in
+    s)
+      [ -z "$OPTARG" ] && usage 2
+      serveraddr="$OPTARG"
+      ;;
+    i)
+      [ -z "$OPTARG" ] && usage 3
+      local_port="$OPTARG"
+      ;;
+    g)
+      [ -z "$OPTARG" ] && usage 4
+      gfw_list="$OPTARG"
+      ;;
+    c)
+      [ -z "$OPTARG" ] && usage 5
+      chn_list="$OPTARG"
+      ;;
+    e)
+      [ -z "$OPTARG" ] && usage 6
+      chnexp_list="$OPTARG"
+      ;;
+    b)
+      [ -z "$OPTARG" ] && usage 7
+      black_ip=$(echo "$OPTARG" | sed 's/,/ /g')
+      ;;
+    w)
+      [ -z "$OPTARG" ] && usage 8
+      white_ip=$(echo "$OPTARG" | sed 's/,/ /g')
+      ;;
+    a)
+      [ -z "$OPTARG" ] && usage 9
+      agentmode_diversionrate="$OPTARG"
+      agent_mode=${agentmode_diversionrate:0:1}
+      [ "$agent_mode" == "2" ] && diversion_rate=${agentmode_diversionrate:1:1} && DR1="$diversion_rate" && DR2=$(expr $DR1 \* 2)
+      ;;
+    t)
+      flush_rules 2>/dev/null && gen_ipset && ipt_nat && ipt_filter
+      ;;
+    m)
+      flush_rules 2>/dev/null && gen_ipset && ipt_nat && ipt_filter && ipt_mangle
+      ;;
+    f)
+      flush_rules 2>/dev/null
+      ;;
+    h)
+      usage 0
+      ;;
+  esac
 done
 
-[ -z "$server" -o -z "$local_port" ] && usage 2
-
-if [ "$TPROXY" = 1 ]; then
-	unset SERVER
-	LOCAL_PORT=$local_port
-elif [ "$TPROXY" = 2 ]; then
-	: ${SERVER:?"You must assign an ip for the udp relay server."}
-	: ${LOCAL_PORT:?"You must assign a port for the udp relay server."}
-fi
-
-flush_rules && ipset_init && ipt_nat && ipt_mangle && export_ipt_rules
-RET=$?
-[ "$RET" = 0 ] && loger 5 "Start Success!" || loger 3 "Start failed!"
-exit $RET
+EC=$?
+[ $EC -eq 0 ] && logger -st "SSP[$$]Rules" "任务成功" || logger -st "SSP[$$]Rules" "任务失败!错误代码:$EC"
+exit $EC
